<?php
//tabla de configyracion para rutas y constantes
define('aliasdb','');
define('from', '/home/mascotasalfalfa/domains/ww2.mascotasalfalfa.com/public_html/image');
define('to', '/home/mascotasalfalfa/domains/crm.mascotasalfalfa.com/public_html/assets/uploads');
define('barcode', 'code128');
define('tax_class_id', 10);
define('tax_class_id_dos', 11);
define('tax_class_id_tres', 12);
define('tax_rate_id', 4);
define('tax_rate_id_dos', 2);
define('tax_rate_id_tres', 3);
define('unit', 1);
define('cost', 0);
define('limit', 1000);
define('valor_cero', 0);
define('valor_uno', 1);
define('valor_dos', 2);
define('valor_tres', 3);
define('tienda_uno', 1);
define('tienda_dos', 2);
define('var_null', 'NULL');
define('string_vacio', '');
define('addition', 'addition');
define('group_name', 'customer');
define('customer_group_name', 'General');
define('valor_guion', '-');
define('correo', 'info@int.com');
define('telefono','9500000000');
define('vendedor','StrongCages S.L.');
define('status_venta','completed');
define('pending','pending');
define('completed','completed');
define('standard','standard');
define('diez_porciento','10%');
define('product_unit_code','Ud');
define('cuatro_porciento','4%');
define('veintiuno_porciento','21%');
define('pagado','paid');